### PR TITLE
Improve performance by doing DP instead of bruteforce

### PR DESCRIPTION
**Pull request by Stanley00**
Only generate valid expression by get_next_values function
Doing BFS on graph of valid expression to find shortest path from starting point (0) to desired_value
Performance improve by about 4x~5x on my PC

### CODE REVIEW

**Comment by dangoldin** [comment]
Hmm - it ran slower on mine for the following example:

```
nums = [9, 25, 5, 7, 3, 8]
desired_result = 799
```

What are the specs of your computer and what test did you run it on? I'm sure it will vary from one test case vs another.

**Comment by dangoldin** [comment]
Feel free to add it as another file though and I'll merge it in for someone else to compare.

**Comment by Stanley00** [comment]
image

This is the cpu info and my test run for testcase [9, 25, 5, 7, 3, 8]. It takes about 6 mins with your code, and about 3 mins for mine. But yeah, since we only find the first solution, the run time will be vary, depends on the path we choose and where is the solution.

**Comment by Stanley00** [comment]
image
I noticed that with python 3, the performance is really slow. This is my try on improving performance on python3. I will update the code when I find a way then.

**Comment by Stanley00** [comment]
image

I added my final code to make it faster on python 3 now. Please review

**Review by dangoldin — APPROVED** [review]

**Comment by dangoldin** [comment]
@Stanley00 Thanks for the improvements. Works much faster now. It also looks as if the safe_f function can be removed since it's not being used.

**Pull request merged**
